name: Auto Update Gallery

on:
  # Disabled automatic schedule - uncomment to re-enable
  # schedule:
  #   # Run every hour
  #   - cron: '0 * * * *'
  workflow_dispatch:  # Keep manual trigger available
  push:
    paths:
      - '.github/workflows/auto-update-gallery.yml'

jobs:
  update-gallery:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install dependencies
      run: |
        npm install playwright
        npx playwright install chromium
    
    - name: Install Netlify CLI
      run: npm install -g netlify-cli
    
    - name: Login to Netlify
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      run: |
        netlify login --auth $NETLIFY_AUTH_TOKEN
    
    - name: Check for new deployments
      run: |
        node auto-detect-deployments.js
    
    - name: Commit and push changes
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add -A
        if git diff --cached --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Auto-update: Add new Netlify deployments"
          git push
        fi